FROM alpine:latest

# Installation de bash et redis
RUN apk add --no-cache bash redis

# Copie le script producer
COPY producer.sh /srv/

# Définie le dossier de travail
WORKDIR /srv

# Lance le producer au démarrage du conteneur
CMD ["bash", "-c", "./producer.sh"]
