FROM alpine:latest
# Alpine = image légère, parfaite pour des scripts Bash + Redis CLI

# Installation de bash et redis-cli
RUN apk add --no-cache bash redis

# On copie le script consumer dans le conteneur
COPY consumer.sh /srv/

# On définit le dossier de travail
WORKDIR /srv

# Commande exécutée automatiquement au démarrage du conteneur
CMD ["bash", "-c", "./consumer.sh"]
