FROM alpine:latest

# Installer bash et redis
RUN apk add --no-cache bash redis

# Copier le script producer
COPY producer.sh /srv/

# Définir le dossier de travail
WORKDIR /srv

# Lancer le producer au démarrage du conteneur
CMD ["bash", "-c", "./producer.sh"]
