# Utiliser l'image Nginx latest comme image de base
FROM nginx:latest

# Copier le fichier default.conf dans le répertoire de configuration de Nginx
COPY default.conf /etc/nginx/conf.d/

# Exposer le port 80
EXPOSE 80
