name: tests unitaires
on: [push]
jobs:
  test1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8","3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python for Demo
        uses: actions/setup-python@v4
        with: 
          python-version: ${{ matrix.python-version}}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run tests
        run: pytest TP1/test.py
      - name : lancement des variable
        run: |
          echo 'Nom de la branche ${{ github.ref }}'
          echo "Nom du repo ${{ github.repository}}"
          echo "L'os utilsié  ${{ runner.os }}"
